<#
.SYNOPSIS
  AgentTreasury CORE — Local Demo (Anvil + Forge + Backend)
  Deploys contracts, configures .env, starts backend, runs demo requests.

.DESCRIPTION
  1. Starts Anvil (local Ethereum devnet)
  2. Deploys MockUSDt + TreasuryVault + CreditLine via Forge
  3. Writes backend/.env with deployed addresses
  4. Starts backend Express server
  5. Sends demo API requests to show the system working

.NOTES
  Prerequisites: Node.js, Foundry (forge + anvil), OpenAI API key
  Run from project root: .\scripts\demo-local.ps1
#>

param(
    [string]$OpenAIKey = $env:OPENAI_API_KEY,
    [switch]$SkipAnvil,
    [switch]$SkipDeploy
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ROOT = Split-Path -Parent $PSScriptRoot
$FORGE = Join-Path $env:USERPROFILE '.foundry\bin\forge.exe'
$ANVIL = Join-Path $env:USERPROFILE '.foundry\bin\anvil.exe'

Write-Host "`n=== AgentTreasury CORE — Local Demo ===" -ForegroundColor Cyan
Write-Host "Project: $ROOT`n"

# ── 0. Validate prerequisites ──
if (-not (Test-Path $FORGE)) {
    Write-Host "ERROR: forge not found at $FORGE" -ForegroundColor Red
    Write-Host "Install Foundry: https://getfoundry.sh" 
    exit 1
}
if (-not $OpenAIKey) {
    Write-Host "WARNING: No OPENAI_API_KEY set. LLM reasoning will be disabled." -ForegroundColor Yellow
    Write-Host "  Set via: `$env:OPENAI_API_KEY = 'sk-...'" 
    $OpenAIKey = "sk-demo-placeholder"
}

# ── 1. Start Anvil ──
$anvilJob = $null
if (-not $SkipAnvil) {
    Write-Host "`n[1/5] Starting Anvil (local devnet)..." -ForegroundColor Green
    $anvilJob = Start-Job -ScriptBlock {
        param($anvil)
        & $anvil --host 127.0.0.1 --port 8545 --accounts 10 --balance 10000 2>&1
    } -ArgumentList $ANVIL
    Start-Sleep -Seconds 2    # Wait for Anvil to be ready

    # Verify Anvil is running
    try {
        $resp = Invoke-RestMethod -Uri 'http://127.0.0.1:8545' -Method Post -ContentType 'application/json' `
            -Body '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' -ErrorAction Stop
        Write-Host "  Anvil running. Chain ID: $($resp.result)" -ForegroundColor DarkGreen
    }
    catch {
        Write-Host "ERROR: Anvil failed to start" -ForegroundColor Red
        exit 1
    }
}
else {
    Write-Host "`n[1/5] Skipping Anvil (--SkipAnvil)" -ForegroundColor Yellow
}

# ── 2. Deploy contracts ──
$addresses = @{}
if (-not $SkipDeploy) {
    Write-Host "`n[2/5] Deploying contracts to Anvil..." -ForegroundColor Green
    Push-Location $ROOT
    try {
        $output = & $FORGE script contracts/script/DeployLocal.s.sol:DeployLocal `
            --rpc-url http://127.0.0.1:8545 --broadcast 2>&1 | Out-String

        # Parse deployed addresses from forge output
        foreach ($line in $output -split "`n") {
            if ($line -match '^\s*(USDT_ADDRESS|TREASURY_VAULT_ADDRESS|CREDIT_LINE_ADDRESS|AGENT_ADDRESS)=(.+)$') {
                $addresses[$Matches[1]] = $Matches[2].Trim()
            }
        }

        if ($addresses.Count -lt 3) {
            Write-Host "  Deploy output:`n$output" -ForegroundColor DarkGray
            Write-Host "ERROR: Could not parse deployed addresses" -ForegroundColor Red
            exit 1
        }

        foreach ($k in $addresses.Keys | Sort-Object) {
            Write-Host "  $k = $($addresses[$k])" -ForegroundColor DarkGreen
        }
    }
    finally {
        Pop-Location
    }
}
else {
    Write-Host "`n[2/5] Skipping deploy (--SkipDeploy)" -ForegroundColor Yellow
}

# ── 3. Write backend .env ──
Write-Host "`n[3/5] Writing backend/.env..." -ForegroundColor Green

# Anvil account #1 mnemonic (deterministic — NOT secret)
$seedPhrase = "test test test test test test test test test test test junk"

$envContent = @"
# Auto-generated by demo-local.ps1 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')
# Using Anvil local devnet + MockERC20

OPENAI_API_KEY=$OpenAIKey
WDK_SEED_PHRASE=$seedPhrase
RPC_URL=http://127.0.0.1:8545
CHAIN_ID=31337

USDT_ADDRESS=$($addresses['USDT_ADDRESS'])
TREASURY_VAULT_ADDRESS=$($addresses['TREASURY_VAULT_ADDRESS'])
CREDIT_LINE_ADDRESS=$($addresses['CREDIT_LINE_ADDRESS'])
AAVE_POOL_ADDRESS=

PORT=3001
LOG_LEVEL=info
"@

$envPath = Join-Path $ROOT 'backend\.env'
Set-Content -Path $envPath -Value $envContent -Encoding UTF8
Write-Host "  Written to $envPath" -ForegroundColor DarkGreen

# ── 4. Start backend ──
Write-Host "`n[4/5] Starting backend server..." -ForegroundColor Green
Push-Location (Join-Path $ROOT 'backend')

$backendJob = Start-Job -ScriptBlock {
    param($dir)
    Set-Location $dir
    npx ts-node src/index.ts 2>&1
} -ArgumentList (Join-Path $ROOT 'backend')

Start-Sleep -Seconds 5    # Wait for server to start

# Check if backend is up
try {
    $health = Invoke-RestMethod -Uri 'http://localhost:3001/health' -ErrorAction Stop
    Write-Host "  Backend running: $($health.status)" -ForegroundColor DarkGreen
}
catch {
    Write-Host "  Backend may still be starting..." -ForegroundColor Yellow
}

Pop-Location

# ── 5. Demo requests ──
Write-Host "`n[5/5] Running demo requests..." -ForegroundColor Green
Write-Host "─────────────────────────────────────────" -ForegroundColor DarkGray

function Demo-Request {
    param([string]$Method, [string]$Url, [string]$Label, $Body)
    Write-Host "`n► $Label" -ForegroundColor Cyan
    Write-Host "  $Method $Url" -ForegroundColor DarkGray
    try {
        $params = @{
            Uri = $Url
            Method = $Method
            ContentType = 'application/json'
            ErrorAction = 'Stop'
        }
        if ($Body) { $params.Body = ($Body | ConvertTo-Json -Depth 5) }
        $resp = Invoke-RestMethod @params
        $resp | ConvertTo-Json -Depth 5 | Write-Host -ForegroundColor White
    }
    catch {
        Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Red
    }
}

Demo-Request -Method GET -Url 'http://localhost:3001/health' -Label 'Health Check'
Start-Sleep 1

Demo-Request -Method GET -Url 'http://localhost:3001/api/dashboard' -Label 'Dashboard Data'
Start-Sleep 1

Demo-Request -Method POST -Url 'http://localhost:3001/api/treasury/sync' -Label 'Sync Treasury State'
Start-Sleep 1

Demo-Request -Method GET -Url 'http://localhost:3001/api/treasury' -Label 'Treasury State'
Start-Sleep 1

# Use Anvil account #2 as a demo borrower
$borrower = '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC'
Demo-Request -Method POST -Url "http://localhost:3001/api/credit/$borrower/evaluate" -Label "Evaluate Credit ($borrower)"
Start-Sleep 2

Demo-Request -Method GET -Url "http://localhost:3001/api/credit/$borrower" -Label 'Get Credit Profile'
Start-Sleep 1

Demo-Request -Method GET -Url 'http://localhost:3001/api/yield/opportunities' -Label 'Yield Opportunities'
Start-Sleep 1

Demo-Request -Method GET -Url 'http://localhost:3001/api/decisions' -Label 'Agent Decisions (Recent)'

# ── Summary ──
Write-Host "`n─────────────────────────────────────────" -ForegroundColor DarkGray
Write-Host "`n✓ Demo complete!" -ForegroundColor Green
Write-Host "  Backend running at: http://localhost:3001"
Write-Host "  Frontend (if started): http://localhost:5173"
Write-Host "  Anvil RPC: http://127.0.0.1:8545"
Write-Host "`nTo stop: press Ctrl+C or run:" -ForegroundColor Yellow
Write-Host "  Stop-Job *; Remove-Job *`n"

# Keep alive (wait for Ctrl+C)
Write-Host "Press Ctrl+C to stop all services..." -ForegroundColor DarkGray
try {
    while ($true) { Start-Sleep -Seconds 60 }
}
finally {
    Write-Host "`nStopping services..." -ForegroundColor Yellow
    if ($backendJob) { Stop-Job $backendJob -ErrorAction SilentlyContinue; Remove-Job $backendJob -ErrorAction SilentlyContinue }
    if ($anvilJob) { Stop-Job $anvilJob -ErrorAction SilentlyContinue; Remove-Job $anvilJob -ErrorAction SilentlyContinue }
    Write-Host "Done." -ForegroundColor Green
}
